# Generated by Django 3.2.7 on 2021-09-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210920_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='schedule.subject', verbose_name='Первый предмет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='schedule.subject', verbose_name='Второй предмет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='schedule.subject', verbose_name='Третий предмет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject4', to='schedule.subject', verbose_name='Четвертый предмет'),
        ),
    ]
