# Generated by Django 3.2.7 on 2021-09-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('teacher', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('odd', models.BooleanField(verbose_name='Нечетная неделя')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.day')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.major')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='schedule.subject')),
                ('subject2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='schedule.subject')),
                ('subject3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='schedule.subject')),
                ('subject4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject4', to='schedule.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('telegram_id', models.BigIntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.major')),
            ],
        ),
    ]
