# Generated by Django 3.2.7 on 2021-09-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='week',
            name='name',
        ),
        migrations.AlterField(
            model_name='week',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.major', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='schedule.subject', verbose_name='Первый предмет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='schedule.subject', verbose_name='Второй предмет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='schedule.subject', verbose_name='Третий предмет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject4', to='schedule.subject', verbose_name='Четвертый предмет'),
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.year', verbose_name='Курс'),
        ),
    ]
