# Generated by Django 3.2.7 on 2021-09-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210920_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='week',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='week',
            name='subject4',
        ),
        migrations.AddField(
            model_name='week',
            name='subject1_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='week',
            name='subject1_teacher',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='week',
            name='subject2_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='week',
            name='subject2_teacher',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='week',
            name='subject3_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='week',
            name='subject3_teacher',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='week',
            name='subject4_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='week',
            name='subject4_teacher',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
