# Generated by Django 3.2.7 on 2021-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20210920_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='subject1_place',
            field=models.CharField(blank=True, max_length=40, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='week',
            name='subject2_place',
            field=models.CharField(blank=True, max_length=40, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='week',
            name='subject3_place',
            field=models.CharField(blank=True, max_length=40, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='week',
            name='subject4_place',
            field=models.CharField(blank=True, max_length=40, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject1_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Первый предмет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject1_teacher',
            field=models.CharField(blank=True, max_length=40, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject2_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Второй предмет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject2_teacher',
            field=models.CharField(blank=True, max_length=40, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject3_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Третий предмет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject3_teacher',
            field=models.CharField(blank=True, max_length=40, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject4_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Четвертый предмет'),
        ),
        migrations.AlterField(
            model_name='week',
            name='subject4_teacher',
            field=models.CharField(blank=True, max_length=40, verbose_name='Преподаватель'),
        ),
    ]
