# Generated by Django 3.2.7 on 2021-09-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210921_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.AlterField(
            model_name='major',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
