# Generated by Django 3.2.7 on 2021-09-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20210925_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ManyToManyField(to='schedule.Major'),
        ),
    ]
