# Generated by Django 3.2.7 on 2021-09-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_major_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.major')),
            ],
        ),
        migrations.AlterField(
            model_name='week',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Курс'),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.AddField(
            model_name='week',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.group'),
        ),
    ]
