# Generated by Django 3.2.7 on 2021-09-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20210925_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='major',
        ),
        migrations.RemoveField(
            model_name='week',
            name='year',
        ),
    ]
