# Generated by Django 3.2.7 on 2021-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_student_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='option',
            field=models.IntegerField(null=True, verbose_name='Вариант'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
